# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
#   - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
#   - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd.yml
#   - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/windows.yml
#   - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux-qt6.yml
#   - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd-qt6.yml
  - project: sysadmin/ci-utilities
    ref: work/kloecker/craft-appimage
    file:
      - /gitlab-templates/craft-appimage.yml
  - project: sysadmin/ci-utilities
    ref: work/kloecker/craft-windows
    file:
      - /gitlab-templates/craft-windows-x86-64.yml


.craft_build_windows_qt515:
  stage: deploy
  image: kdeorg/windows-msvc2019-qt515:latest
  tags:
    - Windows
  variables:
    PYTHONUTF8: 1
    CRAFT_BASE: "C:/Craft"
    CRAFT_PLATFORM: windows-msvc2019_64-cl
    CRAFT_BUILD_BLUEPRINT: ${CI_PROJECT_NAME}
    CRAFTMASTER_CONFIG: ci-utilities/resources/CraftConfig.ini
  interruptible: true
  before_script:
    - cd "$CRAFT_BASE"
    - python craftmaster/Craftmaster.py --setup --config "${CRAFTMASTER_CONFIG}" --target ${CRAFT_PLATFORM} -c --set version=master ${CRAFT_BUILD_BLUEPRINT}
    - python craftmaster/Craftmaster.py --config "${CRAFTMASTER_CONFIG}" --target ${CRAFT_PLATFORM} -c --set branch=${CI_COMMIT_REF_NAME} ${CRAFT_BUILD_BLUEPRINT}
    # Update Craft itself
    - python craftmaster/Craftmaster.py --config "${CRAFTMASTER_CONFIG}" --target ${CRAFT_PLATFORM} -c -i --options virtual.ignored=True --update craft
    # Make sure NSIS is installed (TODO: Pre-install nsis in the Docker image)
    - python craftmaster/Craftmaster.py --config "${CRAFTMASTER_CONFIG}" --target ${CRAFT_PLATFORM} -c (-split ${CRAFT_OPTIONS}) nsis
    # Make sure the build environment for this application is clean
    - python craftmaster/Craftmaster.py --config "${CRAFTMASTER_CONFIG}" --target ${CRAFT_PLATFORM} -c (-split ${CRAFT_OPTIONS}) (-split ${CRAFT_PROJECT_PARAMS}) --unmerge ${CRAFT_BUILD_BLUEPRINT} (-split ${CRAFT_REBUILD_BLUEPRINT})
  script:
    - cd "$CRAFT_BASE"
    # Ask Craftmaster to ensure all the dependencies are installed for this application we are going to be building
    - python craftmaster/Craftmaster.py --config "${CRAFTMASTER_CONFIG}" --target ${CRAFT_PLATFORM} -c (-split ${CRAFT_OPTIONS}) (-split ${CRAFT_PROJECT_PARAMS}) --install-deps ${CRAFT_BUILD_BLUEPRINT}
    # Actually build the application now
    - python craftmaster/Craftmaster.py --config "${CRAFTMASTER_CONFIG}" --target ${CRAFT_PLATFORM} -c (-split ${CRAFT_OPTIONS}) --no-cache (-split ${CRAFT_PROJECT_PARAMS}) --src-dir ${CI_PROJECT_DIR} -vv ${CRAFT_BUILD_BLUEPRINT} (-split ${CRAFT_REBUILD_BLUEPRINT})
  after_script:
    # Ensure gpg-agent and dbus-daemon are no longer around
    # For reasons unknown, these processes somehow end up running within the Binary Factory environment
    # If they're allowed to continue running, then later cleanup operations will fail and leave the builder setup broken (requiring manual intervention to fix)
    - taskkill /F /IM gpg-agent.exe; $null
    - taskkill /F /IM dbus-daemon.exe; $null
    - cd "$CRAFT_BASE"
    - python craftmaster/Craftmaster.py --config "${CRAFTMASTER_CONFIG}" --target ${CRAFT_PLATFORM} -c (-split ${CRAFT_OPTIONS}) --clean-unused
  when: manual

# Nightly win64 craft build of Kate
craft_nightly_windows_qt515:
  extends: .craft_build_windows_qt515
  variables:
    CRAFT_BUILD_TYPE: Nightly

craft_playground:
  stage: deploy
  when: manual
  image: kdeorg/windows-msvc2019-qt515:latest
  tags:
    - Windows
  variables:
    PYTHONUTF8: 1
    GIT_STRATEGY: none
    KDECI_CRAFT_PLATFORM: windows-msvc2019_64-cl
    KDECI_CRAFT_CACHE: C:/Gitlab/Craft/download/
    KDECI_CRAFT_CONFIG: ci-utilities/resources/CraftConfig.ini
    KDECI_CRAFT_PROJECT_CONFIG: $CI_PROJECT_DIR/src/.craft.ini
  interruptible: true
  before_script:
    - git clone $env:CI_REPOSITORY_URL --branch=$env:CI_COMMIT_REF_NAME src/
    # Create empty .craft.ini if none exists
    - if (!(Test-Path $env:KDECI_CRAFT_PROJECT_CONFIG)) { New-Item $env:KDECI_CRAFT_PROJECT_CONFIG -ItemType file }
    - cd C:\Gitlab\Craft\
    - Get-ChildItem C:\Gitlab\Craft\ | Remove-Item -Recurse -Force
    - git clone https://invent.kde.org/packaging/craftmaster --branch=master
    - git clone https://invent.kde.org/sysadmin/ci-utilities
    # Define a short cut for the lengthy CraftMaster command line
    - function Run-CraftMaster { python craftmaster/CraftMaster.py --config $env:KDECI_CRAFT_CONFIG --config-override $env:KDECI_CRAFT_PROJECT_CONFIG --target $env:KDECI_CRAFT_PLATFORM $args }
    # Get Craft itself ready
    - Run-CraftMaster -c -i --options virtual.ignored=True --update craft
  script:
    - $packageAppx = Run-CraftMaster -c --get subinfo.options.dynamic.packageAppx $env:CI_PROJECT_NAME
    - echo $packageAppx
    - if ($packageAppx -eq "True") { echo "Package as AppX" } else { echo "Skip packaging as AppX" }
